# Generated by Django 3.2.5 on 2021-07-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20210722_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
    ]
