# Generated by Django 3.2.5 on 2021-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20210723_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='real_account',
            field=models.BooleanField(default=True),
        ),
    ]
