# Generated by Django 3.2.5 on 2021-07-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_customuser_real_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='accept_status',
            new_name='is_accept',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(blank=True, upload_to='certificates/image/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
