# Generated by Django 3.2.5 on 2021-07-24 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_auto_20210723_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='made_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
