# Generated by Django 3.2.5 on 2021-07-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_certificate_made_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='payment_status',
            new_name='is_paid',
        ),
    ]
