# Generated by Django 3.2.5 on 2021-07-26 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_certificate_is_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='paid_by_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
