# Generated by Django 3.2.5 on 2021-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_certificate_paid_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='website', max_length=255, verbose_name='Тип приложения')),
                ('site_name', models.CharField(default='MoCert', max_length=255, verbose_name='Название сайта')),
                ('title', models.CharField(default='Заработай вместе с нами', max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(default='Перейди по ссылке и получи сертификат', max_length=255, verbose_name='Описание')),
                ('locale', models.CharField(default='ru', max_length=255, verbose_name='Локаль')),
                ('twitter_creator', models.CharField(default='@MonteCarlo', max_length=255, verbose_name='twitter_creator')),
                ('url', models.URLField(default='www.example.com', max_length=255, verbose_name='Ссылка на сайт')),
                ('image', models.URLField(default='www.example.com', max_length=255, verbose_name='Ссылка на картинку')),
            ],
            options={
                'verbose_name': 'Настройки превью',
                'verbose_name_plural': 'Настройки превью',
            },
        ),
    ]
