# Generated by Django 3.2.5 on 2021-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_previewsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previewsettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='image',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='twitter_creator',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='type',
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='url',
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='index_number',
            field=models.PositiveIntegerField(default=0, verbose_name='порядковый номер на странице'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(blank=True, upload_to='certificates/image/%Y/%m/%d', verbose_name='Рисунок'),
        ),
        migrations.AlterField(
            model_name='previewsettings',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
