# Generated by Django 3.2.5 on 2021-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_auto_20210727_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.PositiveIntegerField(verbose_name='порядковый номер на странице')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
        ),
        migrations.AlterModelOptions(
            name='previewsettings',
            options={'verbose_name': 'Настройки превью', 'verbose_name_plural': 'Настройки превью'},
        ),
        migrations.RemoveField(
            model_name='previewsettings',
            name='index_number',
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='description',
            field=models.CharField(default='Перейди по ссылке и получи сертификат', max_length=255, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='image',
            field=models.URLField(default='http://127.0.0.1:8000/media/2607211245970578.png', help_text='Данное поле для всех страниц. Для сертификатов подставляется своя картинка', max_length=255, verbose_name='Ссылка на картинку'),
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='locale',
            field=models.CharField(default='ru', max_length=255, verbose_name='Локаль'),
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='site_name',
            field=models.CharField(default='MoCert', max_length=255, verbose_name='Название сайта'),
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='twitter_creator',
            field=models.CharField(default='@MonteCarlo', max_length=255, verbose_name='twitter_creator'),
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='type',
            field=models.CharField(default='website', max_length=255, verbose_name='Тип приложения'),
        ),
        migrations.AddField(
            model_name='previewsettings',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000', help_text='Данное поле для всех страниц. Для сертификатов подставляется свой url', max_length=255, verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='previewsettings',
            name='title',
            field=models.CharField(default='Заработай вместе с нами', max_length=255, verbose_name='Заголовок'),
        ),
    ]
