# Generated by Django 3.2.5 on 2021-07-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0019_manualposts_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualposts',
            options={'verbose_name': 'Инструкцию', 'verbose_name_plural': 'Инструкции'},
        ),
    ]
