# Generated by Django 3.2.5 on 2021-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_alter_manualposts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualposts',
            name='video',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
