# Generated by Django 3.2.5 on 2021-07-28 05:42

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_alter_manualposts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualposts',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
