# Generated by Django 3.2.5 on 2021-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_mainpagepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagepost',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='mainpagepost',
            name='subtitle',
            field=models.CharField(default=0, max_length=255, verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
    ]
