# Generated by Django 3.2.5 on 2021-07-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_alter_mainpagepost_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagepost',
            name='headline',
            field=models.CharField(max_length=36, verbose_name='Заголовок'),
        ),
    ]
