# Generated by Django 3.2.5 on 2021-07-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_alter_mainpagepost_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagepost',
            name='headline',
            field=models.CharField(help_text='максимум 36 символов', max_length=36, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpagepost',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='Подзаголовок'),
        ),
    ]
