# Generated by Django 3.2.5 on 2021-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_auto_20210728_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagepost',
            name='subtitle',
            field=models.CharField(max_length=131, verbose_name='Подзаголовок'),
        ),
    ]
