# Generated by Django 3.2.5 on 2021-07-30 04:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0028_alter_mainpagepost_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagepost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание'),
        ),
    ]
