# Generated by Django 3.2.5 on 2021-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0029_alter_mainpagepost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='QiwiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(default='0', max_length=255, verbose_name='secret_key')),
            ],
            options={
                'verbose_name': 'Токен qiwi',
                'verbose_name_plural': 'Токены qiwi',
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='максимум 36 символов', max_length=36, verbose_name='Заголовок')),
            ],
        ),
    ]
