# Generated by Django 3.2.5 on 2021-07-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0030_qiwitoken_userbalance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QiwiToken',
            new_name='QIWISECRET_KEY',
        ),
    ]
