# Generated by Django 3.2.5 on 2021-07-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0031_rename_qiwitoken_qiwisecret_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QIWISECRET_KEY',
            new_name='QiwiSecretKey',
        ),
    ]
