# Generated by Django 3.2.5 on 2021-07-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0032_rename_qiwisecret_key_qiwisecretkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.PositiveBigIntegerField(verbose_name='id транзакции')),
                ('amount', models.PositiveIntegerField(verbose_name='сумма')),
                ('lifetime', models.PositiveIntegerField(verbose_name='время жизни счета')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Оплачено'), (2, 'В ожидании'), (3, 'Отклонено')], default=2, max_length=4)),
            ],
            options={
                'verbose_name': 'Пополнение',
                'verbose_name_plural': 'Пополнения',
            },
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
        migrations.AlterModelOptions(
            name='qiwisecretkey',
            options={'verbose_name': 'Токен qiwi', 'verbose_name_plural': 'Токен qiwi'},
        ),
        migrations.AlterField(
            model_name='qiwisecretkey',
            name='secret_key',
            field=models.CharField(default='Token', max_length=255, verbose_name='secret_key'),
        ),
    ]
