# Generated by Django 3.2.5 on 2021-07-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0033_auto_20210731_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositbalance',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Оплачено'), (2, 'В ожидании'), (3, 'Отклонено')], default=2),
        ),
    ]
