# Generated by Django 3.2.5 on 2021-07-31 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0034_alter_depositbalance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='время создания')),
                ('bill_id', models.PositiveBigIntegerField(verbose_name='id транзакции')),
                ('amount', models.PositiveIntegerField(verbose_name='сумма')),
                ('lifetime', models.PositiveIntegerField(verbose_name='время жизни счета')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Оплачено'), (2, 'В ожидании'), (3, 'Отклонено')], default=2)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пополнение',
                'verbose_name_plural': 'Пополнения',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='время создания')),
                ('amount', models.PositiveIntegerField(verbose_name='сумма')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Исполнено'), (2, 'В ожидании'), (3, 'Отклонено')], default=2)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вывод средств',
                'verbose_name_plural': 'Вывод средств',
            },
        ),
        migrations.DeleteModel(
            name='DepositBalance',
        ),
    ]
